### ISSUE TITLE
Not Sending Emails with own SMTP Server

### ISSUE THREAD

**Issue by Suleman-Elahi** [Graphite-Docs/mailr-client#1]
The tool is not sending emails from my own SMTP server. The sent campaign doesn't show up in the Campaigns section and 0 sent emails are shown on the main dashboard.

**Comment by polluterofminds** [comment]
Hmm, what email server are you using?

**Comment by Suleman-Elahi** [comment]
One by Mailjet

**Comment by polluterofminds** [comment]
Mailjet is not supported out of the box by Nodemailer, which is what Mailr uses behind the scenes. Mailjet is more akin to SendGrid than an individual email smtp like Outlook or Gmail.
